---
- name: "Update packages."
  become: true
  apt:
    force_apt_get: yes
    update_cache : true

- name: Install nodejs prerequisites
  apt:
    name:
      - apt-transport-https
      - gcc
      - g++
      - make
    state: present

- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs version 13 repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x {{ ansible_distribution_release }} main
    state: present
    update_cache: yes

- name: "Install nodejs"
  become: true
  apt:
    name: "nodejs"
    state: present

- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present