---

- name: "Ship tar file to ec2 instance and extract it"
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: ~/

- name: "Install backend server's package."
  npm:
    path: ~/

- name: "Stop currently running app"
  ignore_errors: true
  shell: |
    pm2 stop server
- name: "Start the app"
  shell: |
    pm2 start npm -- start --name server
- name: "Check env TYPEORM_ENTITIES"
  command: 'echo $TYPEFORM_ENTITES'
  register: output1

- name: "Check env TYPEORM_CONNECTION"
  command: 'echo $TYPEFORM_CONNECTION'
  register: output2

- name: "Debug"
  debug:
    msg:
      - "{{ output1.stdout }}"
      - "{{ output2.stdout }}"
